# Generated by Django 5.2.7 on 2025-11-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_profile_bmi_profile_bmi_category_profile_bmr_and_more'),
    ]

    operations = [
    ]
