# Generated by Django 5.2.7 on 2025-11-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20251101_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consumed_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='consumed_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='consumed_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='consumed_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_reset',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
