# Generated by Django 5.2.7 on 2025-11-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_profile_diet_type_profile_family_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='landing.profile'),
        ),
    ]
