# Generated by Django 5.2.7 on 2025-11-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_remove_medicalreport_user_medicalreport_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
